#!/bin/bash
if ! test -f /etc/ssh/ssh_host_rsa_key; then
    ssh-keygen -q -N "" -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key
fi
if ! test -f /etc/ssh/ssh_host_ed25519_key; then
    ssh-keygen -q -N "" -t ed25519 -f /etc/ssh/ssh_host_ed25519_key
fi

mkdir -p /run/sshd

/usr/sbin/sshd -D -e